spring:
  datasource:
    url: jdbc:mysql://nanguo.io:3306/lemall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  elasticsearch:
    uris: nanguo.io:9200
logging:
  level:
    root: info
    org.echonanguo.lemall: debug
logstash:
  host: nanguo.io
