spring:
  datasource:
    url: jdbc:mysql://nanguo.io:3306/lemall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://root:123456@nanguo.io:27017/lemall-portal?authSource=admin&authMechanism=SCRAM-SHA-1
    redis:
      host: nanguo.io # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: 123456 # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: nanguo.io
    port: 5672
    virtual-host: /lemall
    username: lemall
    password: lemall
# 日志配置
logging:
  level:
    root: info
    org.echonanguo.lemall: debug
logstash:
  host: nanguo.io
alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: your appId
  alipayPublicKey: your alipayPublicKey
  appPrivateKey: your appPrivateKey
  returnUrl: http://nanguo.io:8060/#/pages/money/paySuccess
  notifyUrl:
