server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://nanguo.io:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
  data:
    redis:
      host: nanguo.io
      port: 6379
      password: 123456
logging:
  level:
    root: DEBUG  # 所有包默认 DEBUG