server:
  port: 8080
# 开启knife4j生产模式
knife4j:
  production: true
spring:
  datasource:
    url: jdbc:mysql://lemall-mysql:3306/lemall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
  data:
    redis:
      host: lemall-redis
      port: 6379
      password: 123456