services:
  redis:
    image: redis:5.0.14
    container_name: lemall-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWD}
    environment:
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:8.0
    container_name: lemall-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d

  minio:
    container_name: lemall-minio
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data

  drawdb:
    container_name: lemall-drawdb
    image: xinsodev/drawdb
    ports:
      - 3000:80
