services:
  redis:
    image: redis:5.0.14
    container_name: lemall-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWD}
    environment:
      - TZ=Asia/Shanghai
    networks:
      - nanguo

  mysql:
    image: mysql:5.7
    container_name: lemall-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - nanguo


  mongodb:
    image: mongo:5.0.9
    container_name: lemall-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWD}
    networks:
      - nanguo

  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: lemall-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./nacos/logs:/home/nacos/logs  # 持久化日志
      - ./nacos/data:/home/nacos/data              # 持久化数据（单机模式）
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
    networks:
      - nanguo

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: lemall-rabbitmq
    ports:
      - "5672:5672"      # AMQP协议端口
      - "15672:15672"    # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWD}
      - RABBITMQ_DEFAULT_VHOST=${MQ_HOST}
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    networks:
      - nanguo

  elasticsearch:
    container_name: lemall-elasticsearch
    image: elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    #      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - nanguo

  kibana:
    container_name: lemall-kibana
    image: kibana:8.10.4
    environment:
      - I18N_LOCALE=zh-CN
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://lemall-elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - nanguo
    depends_on:
      - elasticsearch

  logstash:
    container_name: lemall-logstash
    image: logstash:8.10.4
    ports:
      - "4560:4560"  # 暴露 debug 端口
      - "4561:4561"  # 暴露 error 端口
      - "4562:4562"  # 暴露 business 端口
      - "4563:4563"  # 暴露 record 端口
    volumes:
      - ./logstash/config:/usr/share/logstash/pipeline
    networks:
      - nanguo

  minio:
    container_name: lemall-minio
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    networks:
      - nanguo

networks:
  nanguo:
    driver: bridge
